# Generated by Django 5.0.7 on 2024-07-30 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_id', models.CharField(max_length=50, unique=True)),
                ('equipment_type', models.CharField(max_length=50)),
                ('type_code', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('aircraft_class', models.CharField(max_length=50)),
                ('gear_type', models.CharField(max_length=50)),
                ('engine_type', models.CharField(max_length=50)),
                ('complex', models.BooleanField()),
                ('high_performance', models.BooleanField()),
                ('pressurized', models.BooleanField()),
                ('taa', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FlightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('from_airport', models.CharField(max_length=50)),
                ('to_airport', models.CharField(max_length=50)),
                ('route', models.TextField(blank=True, null=True)),
                ('time_out', models.TimeField()),
                ('time_off', models.TimeField()),
                ('time_on', models.TimeField()),
                ('time_in', models.TimeField()),
                ('on_duty', models.TimeField()),
                ('off_duty', models.TimeField()),
                ('total_time', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pic', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sic', models.DecimalField(decimal_places=2, max_digits=6)),
                ('night', models.DecimalField(decimal_places=2, max_digits=6)),
                ('solo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cross_country', models.DecimalField(decimal_places=2, max_digits=6)),
                ('nvg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('nvg_ops', models.DecimalField(decimal_places=2, max_digits=6)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('day_takeoffs', models.PositiveIntegerField()),
                ('day_landings_full_stop', models.PositiveIntegerField()),
                ('night_takeoffs', models.PositiveIntegerField()),
                ('night_landings_full_stop', models.PositiveIntegerField()),
                ('all_landings', models.PositiveIntegerField()),
                ('actual_instrument', models.DecimalField(decimal_places=2, max_digits=6)),
                ('simulated_instrument', models.DecimalField(decimal_places=2, max_digits=6)),
                ('hobbs_start', models.DecimalField(decimal_places=2, max_digits=6)),
                ('hobbs_end', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tach_start', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tach_end', models.DecimalField(decimal_places=2, max_digits=6)),
                ('holds', models.PositiveIntegerField()),
                ('dual_given', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dual_received', models.DecimalField(decimal_places=2, max_digits=6)),
                ('simulated_flight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ground_training', models.DecimalField(decimal_places=2, max_digits=6)),
                ('instructor_name', models.CharField(blank=True, max_length=100)),
                ('instructor_comments', models.TextField(blank=True)),
                ('flight_review', models.BooleanField(default=False)),
                ('checkride', models.BooleanField(default=False)),
                ('ipc', models.BooleanField(default=False)),
                ('nvg_proficiency', models.BooleanField(default=False)),
                ('faa_6158', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilotlog.aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='Approach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('runway', models.CharField(max_length=50)),
                ('airport', models.CharField(max_length=50)),
                ('comments', models.TextField(blank=True)),
                ('flight_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approaches', to='pilotlog.flightlog')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('flight_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='pilotlog.flightlog')),
            ],
        ),
    ]
