# Generated by Django 5.0.7 on 2024-07-31 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotlog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approach',
            name='flight_log',
        ),
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
        migrations.RemoveField(
            model_name='person',
            name='flight_log',
        ),
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.AddField(
            model_name='flightlog',
            name='approaches',
            field=models.ManyToManyField(related_name='approaches', to='pilotlog.approach'),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='persons',
            field=models.ManyToManyField(related_name='persons', to='pilotlog.person'),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft', to='pilotlog.aircraft'),
        ),
    ]
