# Generated by Django 5.0.7 on 2024-08-06 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotlog', '0002_remove_approach_flight_log_remove_person_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightlog',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_aircraft', to='pilotlog.aircraft'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='approaches',
            field=models.ManyToManyField(related_name='flight_approaches', to='pilotlog.approach'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='persons',
            field=models.ManyToManyField(related_name='flight_persons', to='pilotlog.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to=settings.AUTH_USER_MODEL),
        ),
    ]
